cc_library(
    name = "address",
    hdrs = [
        "address.hpp",
    ],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "network",
    hdrs = [
        "network.hpp",
    ],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
    deps = [":address"],
)
