cc_library(
    name = "csv_row_interface",
    hdrs = [
        "icsv_row.hpp",
    ],
    strip_include_prefix = "",
    visibility = [":__subpackages__"],
)

cc_library(
    name = "csv_reader_interface",
    hdrs = [
        "icsv_reader.hpp",
    ],
    strip_include_prefix = "",
    visibility = [":__subpackages__"],
)
