cc_library(
    name = "ipv4_geo_app",
    srcs = [
        "src/ipv4_geo_app.cpp",
    ],
    hdrs = [
        "src/ipv4_geo_app.hpp",
    ],
    strip_include_prefix = "",
    visibility = ["//app:__subpackages__"],
    deps = [
        "//app:app_interface",
        "//io:io_manager",
        "//io:io_manager_factory",
    ],
)
